config/routes.rb
Rails.application.routes.draw do
  get 'skills/index'
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  post "/profiles/:profile_id/posts/:post_id/skills/new" ,to:"skills#create"
  post "/profiles/:profile_id/posts/:id/review",to:"posts#rate"
  post "profiles/:id/closed" ,to: "posts#review"
  get'/profiles/:profile_id/posts/:post_id/applicants/:id' ,to: "applicants#show"
  post "/profiles/:profile_id/posts/new" ,to: 'posts#create'
  get "/search",to: 'posts#index'
  post "/profiles/edit", to: "profiles#login"
  root "profiles#index"
  resources :profiles do
    member do
      get :completed
      get :closed
      post :closed
      get :applicants
      post :applicants
      put :login
      patch :login
      get :hire
     
      post :hire
      
    end
    resources :posts do
      member do
        get :review
        post :review
      end
      resources :skills
      resources :applicants
    end
  end
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :post
 
  enum astatus: [:hired,:nothired]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
  has_many :applicants
  has_many :skills
  enum pstatus: [:opened,:closed]
  enum progress: [:completed , :pending]
end

app/models/profile.rb
class Profile < ApplicationRecord
    has_secure_password
    enum role: {buyer: '0',seller: '1'}
    has_many :posts
    
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :post
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  def index
 
    @applicants = Applicant.where(post_id: params[:post_id])

  end
  def show 
   
    @app = Applicant.find(params[:id])
    @app.astatus = 'hired'
    @app.save

    @post =Post.find(params[:post_id])
    @post.seller_id =  @app.profile_id
    @post.pstatus = 'closed'
    @post.progress = 'pending'
    @post.save
    redirect_to profile_posts_path

  end
  def new
    @applicant = Applicant.new
  end
  def create
    @applicant = Applicant.create(profile_id:params[:profile_id],post_id: params[:post_id])
  
    redirect_to "/profiles/#{@applicant.profile_id}/applicants"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:commit] != "search"
      @profile =  Profile.find(params[:profile_id])
      session[:id] = @profile.id
    end
    if params[:commit] == "search"
      @skills = Skill.where("name LIKE ?","%#{params[:name]}%")
      @posts = []
      @skills.each do |i|
        @posts<<i.post
      end
    elsif @profile.role == "buyer"
      @posts =  Profile.find(params[:profile_id]).posts
    else
      @posts = Post.all
    end
  
  end
  def show
    
    @post  = Post.find(params[:id])
    @post.progress = 'completed'
    @post.save
    @posts = Post.all
  end
  def new
    @posts =Post.new
  end
  def create  
    
    @profile = Profile.find(params[:profile_id])
    @post = @profile.posts.create(post_params)
    @post.buyer_id = params[:profile_id]
    @post.save
    profile = Profile.find(params[:profile_id])
    redirect_to profile_posts_path(profile)
  end
  def review
    @posts = Post.find(params[:id])
  end
  def rate
    @post =Post.find(params[:id])
    @post.rate = params[:rate]
    @post.save
    redirect_to "/profiles/#{params[:profile_id]}/posts"
  end
  def search
    
    @skills = Skill.where("name LIKE ?","%#{params[:name]}%")
    @posts = []
    @skills.each do |i|
        @posts<<i.post
    end
   render :index 
   
   
  end
  private
  def post_params
    params.permit(:requirement,:description,:budget,:seller_id,:buyer_id,:profile_id,:pstatus)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all
  end

  def applicants
    @applications= Applicant.where(params[:profile_id])
   
  end
  def new
    @profile =  Profile.new
  end
  def create
  
    @profile  = Profile.create!(profile_params)
    redirect_to root_path
  end
  def edit
    @profile = Profile.find(:id)

  end
  def login
 
    profile = Profile.find_by(email: params[:email])
  
  if profile.present? && profile.authenticate(params[:password])

    redirect_to profile_posts_path(profile), notice: "You successfully logged In"
  else
   flash[ :alert] = "Wrong password or Undefined User"
    redirect_to new_profile_path 
  end
  end 
  def show
    @profiles = Profile.all

  end
  def closed
    @profile = Profile.find(params[:id])
    @posts = @profile.posts
  end
  def completed
    @posts = Post.where(seller_id: params[:id])
  end
  def review
    debugger
  end
  private
  def profile_params
    params.require(:profile).permit(:role,:name,:hired_freelacers,:phone,:email,:password,:country,:pending_projects,:completed_projects,:has_secure_password)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
  end
  def new
    @skill = Skill.new
  end
  def create
    @skill = Skill.create(skill_params)
    redirect_to profile_posts_path
  end
  private
  def skill_params
    params.permit(:name,:perhourrate,:post_id)
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/applicants/index.html.erb
<div  style="margin:0% 10% 0% 10%;padding:5px 0px 5px 0px;">
<% @applicants.each do |app|%>
<div style = "border:2px solid green;margin-top:5px; margin-bottom:2px;padding:30px;background-color:
#d5dbdb ;">
    <h4>Applicant Name</h4>
    <%= Profile.find(app.profile_id).name%><br>
    <%= button_to "Hire", "/profiles/#{params[:profile_id]}/posts/#{params[:post_id]}/applicants/#{app.id}" ,method: :get%>
    </div>
<%end%>
</div>

app/views/applicants/show.html.erb
<h1>this is applicant show </h1> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 
    <title>FinalProject1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color:#FFFF">
    <%= yield %>
  </body>
</html>

app/views/posts/dumy.html.erb
lkfsdgsndk

app/views/posts/edit.html.erb
<%= Post.find(params[:id]).requirement%>
<%debugger%>

app/views/posts/index.html.erb
<% if params[:commit] =="search"%>
    <%@profile = Profile.find(session[:id])%>
<%end%>
<div style="margin:0% 10% 0% 10%;padding:5px 0px 5px 0px;">
<div style="background-color:#8B8000;margin:5px 0px 5px 0px;padding:0px;">
<%=notice%>
</div>
<%if @profile.role == "buyer" %>
    <table>
    <th >
    <%= link_to "Post New", new_profile_post_path(@profile),{ :style =>"margin-right:5px;",:class => "btn btn-success "}%>
    </th>
    <th>
    <%= link_to "Closed Posts", closed_profile_path(@profile) ,{ :class => "btn btn-success " }%>
    </th>
    </table>
<%end%>
 <%if @profile.role =="seller"%>
            <table>
            <th>
            <%= link_to "See previously applied",applicants_profile_path(@profile),{ :class => "btn btn-success "}%>
            <%= link_to "Completed projects",completed_profile_path(@profile),{ :class => "btn btn-success "}%>
            </th>
            <th style= "padding-left:500px"> 
            <%= form_with url: '/search',method: :get do |form|%>
                <td>
                <%= form.text_field :name,{:class =>"form-control"}%>
                </td>
                <td>
                <%= form.submit "search",{ :style=>"margin-left:5px;",:class => "btn btn-success input-group-text "}%>
                </td>
           
            <%end%>
            </th>
            </table>
            
<%end%>
<% @posts.each do |post|%>
    <%if post.pstatus == "opened"%>
<div style = "border:2px solid green;margin-top:5px;margin-bottom:2px;padding:30px;background-color:
#d5dbdb ;">
        <h4>Description</h4>
        <%= post.description%><br>
        <h4>Requirement</h4>
        <%= post.requirement%><br>
        <h4>Budget</h4>
        <%= post.budget%>$<br>
        <%if @profile.role == 'seller'%>
            <h4>Skills Required</h4>
            <% post.skills.each do |skill|%>
                <%= skill.name%> | 
                <%= skill.perhourrate%>$<br>
            <%end%>
            <%= button_to "Apply", "/profiles/#{@profile.id}/posts/#{post.id}/applicants",method: :post %>
        <%else%>
        <table>
        <th>
            <%= button_to "Add more skills" ,"/profiles/#{@profile.id}/posts/#{post.id}/skills/new",method: :get%>
            </th>
            <th>
            <%= button_to "See applications","/profiles/#{@profile.id}/posts/#{post.id}/applicants",method: :get %>
            </th>
            </table>
        <%end%>
</div>
    <%end%>  
<%end%>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post do |post| %>
<div class="input-group" style="margin:10%;margin-left:35%;width:30%;">
    <%= post.text_field :budget,{:class=>"form-control"}%><br>
    <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
    <%= post.label :budget%>
    </div>

    <%= post.text_area :requirement,{:class=>"form-control"}%><br>
    <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px px 4px 0px;" >
    <%= post.label :requirement%>
     </div>

    <%= post.text_area :description,{:class=>"form-control"}%><br>
    <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
    <%= post.label :description%>
     </div>

    <%= post.select :pstatus,options_for_select([['0','opened']]),{include_blank: false},{:class=>"form-control"}%>
    <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
    <%= post.label :pstatus, "Status"%>
    </div>
    <%= post.submit "POST NEW"%>
</div>
<%end%>

app/views/posts/review.html.erb
<%=form_with model: @post do |form|%>
 <div class="input-group" style="margin:10%;margin-left:35%;width:30%;">
    <%= form.number_field :rate,{:class=>"form-control",max:5,min:1}%>
    <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
        <%= form.label :rate%>
    </div>
    <%=form.submit "RATE"%>
    <%end%>

app/views/posts/show.html.erb
<div  style="margin:0% 10% 0% 10%;padding:5px 0px 5px 0px;">
    <% @posts.each do |post|%>
        <%if post.progress == 'completed'%>
        <div style = "margin:0% 10% 0% 10%; border:2px solid green;margin-top:5px;padding:10px;background-color: #d5dbdb ;">
            
            <h4>Description</h4>
            <%= post.description%><br>
            <h4>Reruirement</h4>
            <%= post.requirement%><br>
            <h4>Budget</h4>
            <%= post.budget%>$<br>
            <h4> Rating</h4>
            <%= post.rate%>
        </div>
        <%end%>
    <%end%>
</div>

app/views/profiles/applicants.html.erb
<div  style="margin:0% 10% 0% 10%;padding:5px 0px 5px 0px;background-color:gray;">
<% @applications.each do |a|%>  
        <% post=Post.find(a.post_id)%>
        <% if post.progress != 'completed'%>
                <div style = "margin:0% 10% 0% 10%; border:2px solid green;margin-top:5px;padding:10px;background-color: #d5dbdb ;"> 
                        <h4>Description</h4>
                        <%= post.description%><br>
                        <h4>Reruirement</h4>
                        <%= post.requirement%><br>
                        <h4>Budget</h4>
                        <%= post.budget%>$<br>
                        <p style="color: red;border:2px solid red;width:40%;padding:3px;">Have you completed this project? IF Yes Click below</p>
                        <%= button_to "Yes", "/profiles/#{params[:id]}/posts/#{a.post_id}" ,method: :get%>
                        <h4>Status</h4>
                        <p style="color: green">Pending</p>
                        <h4>Progress</h4>
                        <% if a.astatus == 'hired' %>
                                <p>You are hired for this GIG</p>
                        <%else%>
                                <p>Yet not hired</p>
                        <%end%>
                        <br>
                 </div>
        <%end%>
<%end%>
</div>

app/views/profiles/closed.html.erb
<div  style="margin:0% 10% 0% 10%;padding:5px 0px 5px 0px;">
    <% @posts.each do |post|%>
        <%if post.pstatus == 'closed'%>
            <div style = "margin:0% 10% 0% 10%; border:2px solid green;margin-top:5px;padding:10px;background-color:
            #d5dbdb ;">
                
                <h4>Description</h4>
                <%= post.description%><br>
                <h4>Reruirement</h4>
                <%= post.requirement%><br>
                <h4>Budget</h4>
                <%= post.budget%>$<br>
                <h4>Progress</h4>
                <%if post.progress == 'completed'%>
                    <p>Completed</p>

                    <%if post.rate == nil%>
                        <%= button_to "Give me review", "/profiles/#{post.buyer_id}/posts/#{post.id}/review",method: :get %>
                    <%else%>
                        <h4>Rating</h4>
                        <%= post.rate %>
                    <%end%>
               <%else%>
                    <>
                     <button>Pending</button>
                <%end%>
            <%end%>
        </div>
    <%end%>
</div>

app/views/profiles/completed.html.erb
<div  style="margin:0% 10% 0% 10%;padding:5px 0px 5px 0px;">
<% @posts.each do |post|%>
<div style = "border:2px solid green;margin-top:5px;padding:30px;background-color:
#d5dbdb ;">
    <%if post.progress == 'completed'%>
       
        <h4>Description</h4>
        <%= post.description%><br>
        <h4>Reruirement</h4>
        <%= post.requirement%><br>
        <h4>Budget</h4>
        <%= post.budget%>$<br>
        <h4>Rating</h4>
        <%= post.rate %><br>
            <h4>Skills Required</h4>
            <% post.skills.each do |skill|%>
                <%= skill.name%>    |
                  <%= skill.perhourrate%>$<br>
            <%end%>
        
    <%end%>
    </div>
<%end%>
</div>

app/views/profiles/index.html.erb
<div  style="margin:5%;background-color:black;border:3px solid black;">
    
    <%= link_to "login", profiles_edit_path,{ :style=>"width:100%; padding:10px;margin-bottom:3px;",:class => "btn btn-success "} %>
    <%=  link_to "signup",new_profile_path,{  :style=>"width:100%;padding:10px;",:class => "btn btn-success "}%>
</div>

app/views/profiles/new.html.erb
<%= form_with model: @profile do |form|%>
    <div class="input-group" style="margin:10%;margin-left:35%;width:30%;">
        <div style="background-color:#8B8000;margin:5px 0px 5px 0px;padding:0px;">
        <%=alert%>
        </div>
        <%= form.text_field :name,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :name%>
        </div>
        <%= form.email_field :email,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :email%>
        </div>
        <%= form.text_field :phone ,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :phone%>
        </div>
        <%= form.text_field :country,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :country%>
        </div>
        <%= form.password_field :password ,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :password %>
        </div>
        <%= form.select :role,options_for_select([['buyer','0'],['seller','1']]),{include_blank: false} ,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :role%>
        </div>
        <%= form.submit "SIGN UP"%>  
    </div>
<%end%>

app/views/profiles/show.html.erb
<div>
<%= form_with model: @profile do |form| %>
    <div class="input-group" style="margin:10%;margin-left:35%;width:30%;">
        <%= form.email_field :email,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :email%>
        </div>
        <%= form.password_field :password,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :password%>
        </div>
        <%= form.submit "LOG IN"%>
    </div>
<%end%>
</div>

app/views/skills/index.html.erb
<h1>Skills#index</h1>
<p>Find me in app/views/skills/index.html.erb</p>

app/views/skills/new.html.erb
<%=form_with model: @skills do |form|%>
    <div class="input-group" style="margin:10%;margin-left:35%;width:30%;">
        <%= form.text_field :name ,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :name%>
        </div>
        <%= form.number_field :perhourrate,{:class=>"form-control"}%>
        <div style="background-color: #82e0aa ; padding-left:105px; border-radius:10px;margin:0px 0px 4px 0px;" >
            <%= form.label :perhourrate%>
        </div>
        <%= form.submit "ADD"%>
    </div>
<%end%>